name: Update README ⭐
on:
  schedule:
    - cron: "51 */4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tfeuerbach/aoc-markdown-table@v1.0.5
        with:
          userId: 2435215
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: 2022/README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
